leftnav:
- identifier: 511b29ee-4ef7-afe6-d23d-0c59929b24d1
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 10
- identifier: external-3bb22c0a2ae54b1697dd39835e805b7e
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:OCW+Pre-7.01+1T2020/about
  weight: 1000
